### ISSUE TITLE
Content distribution network on read first option

### ISSUE THREAD

**Issue by posix4e** [mozilla/sccache#175] opened 2017-08-16 01:43 UTC
I'm thinking this is really helpful for the build machines especially with open source(travis).

**Comment by luser** [comment] 2017-08-16 17:43
It might, but it might not. CDNs have a warmup time, and also S3 access from EC2 instances is already incredibly fast. If we get to a point where it's easy for a developer to use sccache and get hits from a cache populated by your CI then having a CDN in front of that might make more sense.

**Comment by glandium** [comment] 2017-08-16 21:47
Note that I'm actually interested in multi-stage caching, for things like:
- S3 + local (download from S3, store locally for next time)
- S3 + S3 (in mozilla case, for try builds, try to get from the cache for inbound/autoland first)

**Comment by posix4e** [comment] 2017-08-16 21:49
For now basedir limits the use of this

**Comment by pietroalbini** [comment] 2019-10-22 18:21
The Rust project would be really interested in seeing this implemented, as our CI runs outside AWS and due to our high CloudFront usage putting a CDN in front of S3 lowers costs from 0.09$/GB to 0.04$/GB, saving hundreds of dollars each month.

If the sccache project is willing to accept it I can write a PR adding support for CDNs.

**Comment by luser** [comment] 2019-10-22 19:22
Rust CI is running in Azure Pipelines nowadays, right? sccache already has an [Azure Blob Storage backend](https://github.com/mozilla/sccache#azure) so it might be easier for you to just configure that for your CI instead.

**Comment by pietroalbini** [comment] 2019-10-23 07:49
If we can get sponsorship for a bucket on Azure, at the moment yes. In the (near?) future we'll probably have to get some builders outside of major cloud providers for non-x86 platforms though, and in that case we'll need something like this anyway.

**Comment by aidanhs** [comment] 2019-10-28 21:06
This relates to https://github.com/mozilla/sccache/issues/30

Some notes on a possible way to implement for the Rust CI use-case:

 - let's say as a strawman there's a `ro_cache` config section, like [`cache`](https://github.com/mozilla/sccache/blob/dc68459/src/config.rs#L403-L406)
 - just as the 'first' working RW cache [is selected](https://github.com/mozilla/sccache/blob/dc6845963af96de3521e60921d2718b99c725d9c/src/server.rs#L402), so should there be something analogous for read only caches. I think you could use exactly the same function if you tweaked the args
 - weave (the optional) `ro_storage` into [get_cached_or_compile](https://github.com/mozilla/sccache/blob/dc6845963af96de3521e60921d2718b99c725d9c/src/compiler/compiler.rs#L142)
 - augment the location where the [write cache is checked](https://github.com/mozilla/sccache/blob/dc6845963af96de3521e60921d2718b99c725d9c/src/compiler/compiler.rs#L177-L181) to instead check the `ro_storage` if it's `Some`

Additional comments:

 - if there's a ro_storage, the design above won't check the write storage at all (for the rust CI use-case, cloudfront in front of s3 would just cache miss twice). It seems reasonable to permit a default-false boolean option (e.g. called `overlay` or `readthrough`) in the `ro_cache` section of the config file to indicate both should be checked. If adding this option you might implement it in the `Server` and `Service` as a vec (max len 2) of `read_storages` and a single `write_storage`. If doing this, you'd likely want to permit the first read storage to error and try again with the second
 - one could add another default-false boolean object (e.g. called `propagate_objects`) to indicate objects retrieved from the read cache should be saved in the write cache to support the [S3->local usecase above](https://github.com/mozilla/sccache/issues/175#issuecomment-322909065)
 - there are many more hypothetical complex cache setups and it likely makes sense to redesign caching configuration if this were to be supported. I can think of a lot of subtlety in specifying the desired behavior of which caches to write to/read from and when (especially as too many read caches will have bad effects on performance). Honestly, it seems rather hard to specify and almost calls for a DSL - it'd be interesting to see what other how other tools handle this level of configurability. I would personally treat this 'ultimate configurability' as out of scope for the common-case implementations outlined above
 - a previous stab at this is in https://github.com/mozilla/sccache/pull/241, I've not looked at it

**Comment by aidanhs** [comment] 2019-10-28 21:16
Oh right, for the second part for the Rust CI use-case (the CDN), you might do something like:

 - create another kind of [cache config](https://github.com/mozilla/sccache/blob/dc68459/src/config.rs#L197-L202) (maybe a 'Url' config) that has a `{}` to indicate where it should be templated
 - when loading the `Url` storage from the config, break the URL apart so you're not dynamically doing the templating every time(!), which also lets you check for validity
 - make [`put`](https://github.com/mozilla/sccache/blob/dc6845963af96de3521e60921d2718b99c725d9c/src/cache/cache.rs#L152) in the storage just always return an error
 - people should now be able to use it in `ro_cache` or `cache` at will

Additional comments:
 - it's kinda odd to allow `Url` in the `cache` section since you can't ever write to it, but as designed above you can't have a `ro_cache` without a `cache` section, so if you only want to cache by attempting to retrieve stuff from a CDN then it has to go in `cache`. I'd propose this is probably fine, and something more elegant would be deferred to the 'ultimately configurable' cache system

**Comment by mihaiplesa** [comment] 2021-01-26 11:12
Any updates on this?

**Closed** 2022-05-10 12:14 UTC
