### ISSUE TITLE
Max concurrent jobs with sccache

### ISSUE THREAD

**Issue by yf225** [mozilla/sccache#248] opened 2018-05-08 00:06 UTC
When using https://github.com/yf225/sccache/commit/336584a9e01c4c95a4396f42b57040025e297faa to compile CUDA source files with  `make -j4` on a 4-core machine, sccache seems to give the following error: 

```
19:04:53 [ 14%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THC/ATen_generated_THCStorage.cu.o
19:04:53 [ 14%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THC/ATen_generated_THCReduceApplyUtils.cu.o
19:04:53 [ 14%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THC/ATen_generated_THCSleep.cu.o
19:04:53 [ 14%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THC/ATen_generated_THCBlas.cu.o
19:15:13 error: failed to execute compile
19:15:13 caused by: error reading compile response from server
19:15:13 caused by: Failed to read response header
19:15:13 caused by: failed to fill whole buffer
19:15:13 error: failed to execute compile
19:15:13 caused by: error reading compile response from server
19:15:13 caused by: Failed to read response header
19:15:13 caused by: failed to fill whole buffer
19:15:17 error: failed to execute compile
19:15:17 caused by: error reading compile response from server
19:15:17 caused by: Failed to read response header
19:15:17 caused by: failed to fill whole buffer
19:15:17 error: failed to execute compile
19:15:17 caused by: error reading compile response from server
19:15:17 caused by: Failed to read response header
19:15:17 caused by: failed to fill whole buffer
```

while `make -j2` seems to work fine for the 4-core machine. Interestingly on a 16-core machine `make -j8` works fine. This issue doesn’t happen when building C++ source files. Curious what might be causing this issue? Thanks!

**Comment by yf225** [comment] 2018-05-08 01:31
Update: setting number of concurrent jobs to `$(nproc)-1` fixes the issue.

**Comment by ezyang** [comment] 2018-05-08 01:45
I'm not sure I would necessarily close this issue? The server shouldn't deadlock even if you have more processes than cpus.

**Comment by luser** [comment] 2018-08-28 15:07
Can you reliably reproduce this? If so, getting a log out of the sccache server would help diagnosing what's happening here. I agree that this should not fail this way. You can get logs by first ensuring that no sccache server is running (`sccache --stop-server`), then starting a server with logging enabled:
`RUST_LOG=sccache=trace SCCACHE_ERROR_LOG=/tmp/sccache.log sccache --start-server`.

**Comment by Marwes** [comment] 2018-10-12 15:05
Found at least one cause for this error that is pretty easy to reproduce.

`sccache` does not do a graceful shutdown when the idle timeout is reached so any compile requests in flight gets aborted and this is the error printed. I'd say the fix for that is to keep track of whether there are in-flight requests and only start the idle timeout when the server is actually idle?

It is possible that there are other problems that cause the same error but that is at least a candidate.

**Comment by luser** [comment] 2018-10-12 15:42
Ah yes, that's https://github.com/mozilla/sccache/issues/204

**Comment by Marwes** [comment] 2018-10-12 17:56
I have observed a deadlock as well which gives this same error. Haven't been able to reproduce it with logs enabled yet though.

**Comment by Marwes** [comment] 2018-10-15 13:10
I believe the deadlock may be https://github.com/alexcrichton/tokio-process/issues/42 so hopefully updating to tokio-process 0.2.5 should fix. Included it in #304 since `cargo update` would conflict with that PR but it could be fixed independently.

**Comment by luser** [comment] 2018-12-10 18:47
This should be fixed since we merged https://github.com/mozilla/sccache/pull/304 . If it reoccurs please let me know!

**Closed by luser** 2018-12-10 18:47 UTC

**Comment by ezyang** [comment] 2018-12-11 04:45
cc @yf225 @bddppq
