### ISSUE TITLE
Feature: read-only cache with rw fallback

### ISSUE THREAD

**Issue by ishitatsuyuki** [mozilla/sccache#229] opened 2018-03-03 13:26 UTC
In some multi-tenant usecase, we may want to use other's cache without the risk to pollute them.

The proposal here is basically a two (and maybe more) tier cache, with at least one read-only sources and exactly one writable cache source.

**Comment by luser** [comment] 2018-03-06 14:56
This is definitely something we'd like to support! We have a related scenario in Firefox CI where we have a "try" branch for people to test changes before landing them, which uses a separate bucket from our main CI for security reasons. It would be nice if builds on the try branch could get cache hits from the other bucket without having write access.

**Comment by luser** [comment] 2018-03-06 14:57
Duplicate of #30

**Closed** 2018-03-06 14:57 UTC
