### ISSUE TITLE
"error reading compile response from server"

### ISSUE THREAD

**Issue by marco-c** [mozilla/sccache#256] opened 2018-06-20 08:05 UTC
I'm compiling Firefox with code coverage enabled (for both C++ and Rust). I guess the size of the Rust library is huge and is causing sccache to OOM?

```
 0:02.53      Running `/home/marco/.cargo/bin/sccache /home/marco/rustc/bin/rustc --crate-name style servo/components/style/lib.rs --color always --crate-type lib --emit=dep-info,link -C opt-level=1 -C panic=abort -C debuginfo=2 -C debug-assertions=on --cfg 'feature="bindgen"' --cfg 'feature="fallible"' --cfg 'feature="gecko"' --cfg 'feature="gecko_debug"' --cfg 'feature="nsstring"' --cfg 'feature="num_cpus"' --cfg 'feature="regex"' --cfg 'feature="style_traits"' --cfg 'feature="toml"' --cfg 'feature="use_bindgen"' -C metadata=83ab44a291a177d3 -C extra-filename=-83ab44a291a177d3 --out-dir /home/marco/Documenti/FD/mozilla-unified/obj-gcc-ccov/toolkit/library/x86_64-unknown-linux-gnu/debug/deps --target x86_64-unknown-linux-gnu -C linker=/home/marco/Documenti/FD/mozilla-unified/build/cargo-linker -L dependency=/home/marco/Documenti/FD/mozilla-unified/obj-gcc-ccov/toolkit/library/x86_64-unknown-linux-gnu/debug/deps -L dependency=/home/marco/Documenti/FD/mozilla-unified/obj-gcc-ccov/toolkit/library/debug/deps --extern app_units=/home/marco/Documenti/FD/mozilla-unified/obj-gcc-ccov/toolkit/library/x86_64-unknown-linux-gnu/debug/deps/libapp_units-3f3afbd10ddd1284.rlib --extern arrayvec=/home/marco/Documenti/FD/mozilla-unified/obj-gcc-ccov/toolkit/library/x86_64-unknown-linux-gnu/debug/deps/libarrayvec-69ab602abd4c6d0b.rlib --extern atomic_refcell=/home/marco/Documenti/FD/mozilla-unified/obj-gcc-ccov/toolkit/library/x86_64-unknown-linux-gnu/debug/deps/libatomic_refcell-4b0de42eae2a384a.rlib --extern bitflags=/home/marco/Documenti/FD/mozilla-unified/obj-gcc-ccov/toolkit/library/x86_64-unknown-linux-gnu/debug/deps/libbitflags-f60c83f33d45b24e.rlib --extern byteorder=/home/marco/Documenti/FD/mozilla-unified/obj-gcc-ccov/toolkit/library/x86_64-unknown-linux-gnu/debug/deps/libbyteorder-d08c50bcc801100c.rlib --extern cfg_if=/home/marco/Documenti/FD/mozilla-unified/obj-gcc-ccov/toolkit/library/x86_64-unknown-linux-gnu/debug/deps/libcfg_if-fa993bdfd8b2209c.rlib --extern cssparser=/home/marco/Documenti/FD/mozilla-unified/obj-gcc-ccov/toolkit/library/x86_64-unknown-linux-gnu/debug/deps/libcssparser-fa23a70d55cee21c.rlib --extern euclid=/home/marco/Documenti/FD/mozilla-unified/obj-gcc-ccov/toolkit/library/x86_64-unknown-linux-gnu/debug/deps/libeuclid-35eef7e7b99fc7ae.rlib --extern fallible=/home/marco/Documenti/FD/mozilla-unified/obj-gcc-ccov/toolkit/library/x86_64-unknown-linux-gnu/debug/deps/libfallible-124f0400d54f5405.rlib --extern fnv=/home/marco/Documenti/FD/mozilla-unified/obj-gcc-ccov/toolkit/library/x86_64-unknown-linux-gnu/debug/deps/libfnv-a263c86f414fe9bc.rlib --extern hashglobe=/home/marco/Documenti/FD/mozilla-unified/obj-gcc-ccov/toolkit/library/x86_64-unknown-linux-gnu/debug/deps/libhashglobe-3043bc9469611914.rlib --extern itertools=/home/marco/Documenti/FD/mozilla-unified/obj-gcc-ccov/toolkit/library/x86_64-unknown-linux-gnu/debug/deps/libitertools-0277fd3ba6904a5c.rlib --extern itoa=/home/marco/Documenti/FD/mozilla-unified/obj-gcc-ccov/toolkit/library/x86_64-unknown-linux-gnu/debug/deps/libitoa-811bac0fd0b296e1.rlib --extern lazy_static=/home/marco/Documenti/FD/mozilla-unified/obj-gcc-ccov/toolkit/library/x86_64-unknown-linux-gnu/debug/deps/liblazy_static-f67b4f726a8ab6a2.rlib --extern log=/home/marco/Documenti/FD/mozilla-unified/obj-gcc-ccov/toolkit/library/x86_64-unknown-linux-gnu/debug/deps/liblog-2ad4921a64f15de4.rlib --extern malloc_size_of=/home/marco/Documenti/FD/mozilla-unified/obj-gcc-ccov/toolkit/library/x86_64-unknown-linux-gnu/debug/deps/libmalloc_size_of-aa65644769e57521.rlib --extern malloc_size_of_derive=/home/marco/Documenti/FD/mozilla-unified/obj-gcc-ccov/toolkit/library/debug/deps/libmalloc_size_of_derive-fd3e204b7a5c8c8f.so --extern matches=/home/marco/Documenti/FD/mozilla-unified/obj-gcc-ccov/toolkit/library/x86_64-unknown-linux-gnu/debug/deps/libmatches-a48c93f61d4649ac.rlib --extern ordered_float=/home/marco/Documenti/FD/mozilla-unified/obj-gcc-ccov/toolkit/library/x86_64-unknown-linux-gnu/debug/deps/libordered_float-b5285d52e0b8a8a1.rlib --extern debug_unreachable=/home/marco/Documenti/FD/mozilla-unified/obj-gcc-ccov/toolkit/library/x86_64-unknown-linux-gnu/debug/deps/libdebug_unreachable-28b05ea231090f9e.rlib --extern nsstring=/home/marco/Documenti/FD/mozilla-unified/obj-gcc-ccov/toolkit/library/x86_64-unknown-linux-gnu/debug/deps/libnsstring-2c1ae6bcdc2fc28d.rlib --extern num_integer=/home/marco/Documenti/FD/mozilla-unified/obj-gcc-ccov/toolkit/library/x86_64-unknown-linux-gnu/debug/deps/libnum_integer-3884622ebe825a37.rlib --extern num_traits=/home/marco/Documenti/FD/mozilla-unified/obj-gcc-ccov/toolkit/library/x86_64-unknown-linux-gnu/debug/deps/libnum_traits-6e601eaa2d589149.rlib --extern num_cpus=/home/marco/Documenti/FD/mozilla-unified/obj-gcc-ccov/toolkit/library/x86_64-unknown-linux-gnu/debug/deps/libnum_cpus-1b8af8cc1aed2e71.rlib --extern owning_ref=/home/marco/Documenti/FD/mozilla-unified/obj-gcc-ccov/toolkit/library/x86_64-unknown-linux-gnu/debug/deps/libowning_ref-cc00be64f7f8a1b8.rlib --extern parking_lot=/home/marco/Documenti/FD/mozilla-unified/obj-gcc-ccov/toolkit/library/x86_64-unknown-linux-gnu/debug/deps/libparking_lot-df54f4283eccc89f.rlib --extern precomputed_hash=/home/marco/Documenti/FD/mozilla-unified/obj-gcc-ccov/toolkit/library/x86_64-unknown-linux-gnu/debug/deps/libprecomputed_hash-15a23ed8abe047cb.rlib --extern rayon=/home/marco/Documenti/FD/mozilla-unified/obj-gcc-ccov/toolkit/library/x86_64-unknown-linux-gnu/debug/deps/librayon-ba38fc3afb8a543a.rlib --extern selectors=/home/marco/Documenti/FD/mozilla-unified/obj-gcc-ccov/toolkit/library/x86_64-unknown-linux-gnu/debug/deps/libselectors-7a8513c9ec49ea80.rlib --extern servo_arc=/home/marco/Documenti/FD/mozilla-unified/obj-gcc-ccov/toolkit/library/x86_64-unknown-linux-gnu/debug/deps/libservo_arc-fef4dcb2d61bee94.rlib --extern smallbitvec=/home/marco/Documenti/FD/mozilla-unified/obj-gcc-ccov/toolkit/library/x86_64-unknown-linux-gnu/debug/deps/libsmallbitvec-a0d6a9143f87dab5.rlib --extern smallvec=/home/marco/Documenti/FD/mozilla-unified/obj-gcc-ccov/toolkit/library/x86_64-unknown-linux-gnu/debug/deps/libsmallvec-2ccb96d8546c2ddc.rlib --extern style_derive=/home/marco/Documenti/FD/mozilla-unified/obj-gcc-ccov/toolkit/library/debug/deps/libstyle_derive-c3889f7e3e249276.so --extern style_traits=/home/marco/Documenti/FD/mozilla-unified/obj-gcc-ccov/toolkit/library/x86_64-unknown-linux-gnu/debug/deps/libstyle_traits-9c09104156f83ee6.rlib --extern time=/home/marco/Documenti/FD/mozilla-unified/obj-gcc-ccov/toolkit/library/x86_64-unknown-linux-gnu/debug/deps/libtime-9631d0d9f99a880e.rlib --extern uluru=/home/marco/Documenti/FD/mozilla-unified/obj-gcc-ccov/toolkit/library/x86_64-unknown-linux-gnu/debug/deps/libuluru-6ead0d2cdd210750.rlib --extern unicode_bidi=/home/marco/Documenti/FD/mozilla-unified/obj-gcc-ccov/toolkit/library/x86_64-unknown-linux-gnu/debug/deps/libunicode_bidi-b42011b6c7f1aa9d.rlib --extern unicode_segmentation=/home/marco/Documenti/FD/mozilla-unified/obj-gcc-ccov/toolkit/library/x86_64-unknown-linux-gnu/debug/deps/libunicode_segmentation-d99ea7687f675e31.rlib --extern void=/home/marco/Documenti/FD/mozilla-unified/obj-gcc-ccov/toolkit/library/x86_64-unknown-linux-gnu/debug/deps/libvoid-c0432b5e4309bf29.rlib -C opt-level=1 -C debuginfo=2 -Ccodegen-units=1 -Clink-dead-code -Zprofile -Zno-landing-pads`
10:12.69 error: failed to execute compile
10:12.69 caused by: error reading compile response from server
10:12.69 caused by: Failed to read response header
10:12.69 caused by: failed to fill whole buffer
10:12.70 error: Could not compile `style`.
```

**Comment by marco-c** [comment] 2018-06-20 08:07
Similar to https://bugzilla.mozilla.org/show_bug.cgi?id=1415526.

**Comment by marco-c** [comment] 2018-06-20 08:10
Or maybe compilation is taking too long, I've tried to increase SCCACHE_IDLE_TIMEOUT to 1500.

**Comment by ezyang** [comment] 2018-06-21 02:39
This seems to happen to us when we attempt to do too many parallel builds. Reducing parallelism helps.

**Comment by aidanhs** [comment] 2018-06-21 21:50
I've observed an sccache test failing with a similar error and I've tracked it down to the local daemon segfaulting, reproduced in https://github.com/rust-lang/rust/issues/47551.

If you're able to reliably reproduce, you can also try starting an sccache server in the foreground in a separate terminal with `RUST_LOG=sccache=trace RUST_BACKTRACE=1 SCCACHE_NO_DAEMON=1 SCCACHE_START_SERVER=1 sccache` and then see the last few messages. The problem that I see is characterised by the following few lines:
```
TRACE:sccache::compiler::c: [test.o]: Preprocessor output is 12930 bytes
DEBUG:sccache::compiler::compiler: [test.o]: generate_hash_key took 0.006 s
TRACE:sccache::compiler::compiler: [test.o]: Hash key: a2213989517bb6203ba6f8c91ee3b4902bd2b34128e5e3275f749303d06acf72c8b1a027b39d2e096989741246db003520c49036772bf25f91c5aec0270384bb
TRACE:sccache::cache::disk: DiskCache::get(a2213989517bb6203ba6f8c91ee3b4902bd2b34128e5e3275f749303d06acf72c8b1a027b39d2e096989741246db003520c49036772bf25f91c5aec0270384bb)
DEBUG:sccache::compiler::compiler: [test.o]: Cache hit in 0.000 s
signal 11 received
Segmentation fault (core dumped)
```

**Comment by marco-c** [comment] 2018-06-21 21:53
In my case it was actually taking too long to compile, increasing the timeout fixed the problem.

**Comment by luser** [comment] 2018-10-12 15:42
Then this is a duplicate of https://github.com/mozilla/sccache/issues/204

**Closed by luser** 2018-10-12 15:42 UTC

**Comment by joelparkerhenderson** [comment] 2020-06-19 04:14
Novice question: how do I follow the instructions above to try setting SCCACHE_IDLE_TIMEOUT to something larger?

I just started using sccache, and the error message is happening when rustc compiles Diesel, which in my project uses a bunch of features, and has always spent upwards of 15 minutes to compile.

**Comment by mszhanyi** [comment] 2022-03-01 04:17
try setting SCCACHE_IGNORE_SERVER_IO_ERROR=1

**Comment by mitchhentges** [comment] 2022-03-01 14:41
> try setting SCCACHE_IGNORE_SERVER_IO_ERROR=1

This will cause the underlying error to be ignored and performance to suffer.
For cases like this, the correct solution is to find out _why_ the server couldn't be communicated with :)
