### ISSUE TITLE
sccache does not work with docker build

### ISSUE THREAD

**Issue by BenD0G** [mozilla/sccache#891] opened 2020-11-28 13:47 UTC
Edit: this appears to be a symptom of https://github.com/mozilla/sccache/issues/887 - changing the first line of the dockerfile to `FROM rust:1.47` fixes the issue. Leaving open as I imagine the recent change to `latest` tag on `rust` images will catch others out too.

`sccache` does not appear to work at all in build instructions of dockerfiles - depending on what I try I get errors about sending data to the server, connecting to the server or timeouts waiting for the `sccache` server to start.

I could have sworn this used to work, but I've tried many variations, and building on both WSL (`Docker version 19.03.12, build 48a66213fe`) and on Docker Desktop for Windows (`Docker version 19.03.13, build 4484c46d9d`), all with the same output as below.

`sccache --version`: `sccache 0.2.13`

Any help would be greatly appreciated!

## Sample Dockerfile and Output
Dockerfile:

```dockerfile
FROM rust
RUN cargo install sccache
ENV RUSTC_WRAPPER=/usr/local/cargo/bin/sccache
RUN USER=root cargo init hello_world
WORKDIR /hello_world
RUN cargo build
```
Output:
```
<snip>
#8 [5/5] RUN cargo build
#8 0.365 error: failed to run `rustc` to learn about target-specific information
#8 0.365
#8 0.365 Caused by:
#8 0.365   process didn't exit successfully: `/usr/local/cargo/bin/sccache rustc - --crate-name ___ --print=file-names --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg` (exit code: 2)
#8 0.365   --- stderr
#8 0.365   error: failed to execute compile
#8 0.365   caused by: Failed to send data to or receive data from server
#8 0.365   caused by: Failed to read response header
#8 0.365   caused by: failed to fill whole buffer
#8 ERROR: executor failed running [/bin/sh -c cargo build]: runc did not terminate sucessfully
```

**Comment by martin-foerster-rhebo** [comment] 2020-12-01 13:53
We face exactly the same problem and in our case this was also a symptom of #887.

**Comment by glandium** [comment] 2020-12-11 04:42
Duplicate of #875

**Closed by glandium** 2020-12-11 04:42 UTC
