### ISSUE TITLE
sccache does not realise that a rust compiler version has been changed by rustup

### ISSUE THREAD

**Issue by aidanhs** [mozilla/sccache#856] opened 2020-09-27 17:52 UTC
Specifically if doing `rustup update nightly`. This is probably because the path remains the same, and

An easy fix would just be to perform a single check of the mtime of some part of Rust every time when invoking the Rust compiler (being cautious that we're not checking the rustup wrapper binary).

**Comment by drahnr** [comment] 2020-09-28 12:03
This is a duplicate of #853

**Comment by ryankurte** [comment] 2020-11-10 21:12
is this compiler detection by any chance the cause of the following error with `v0.2.13`?

```
$ cargo +nightly build --target $TARGET --release $OPTIONS
error: failed to run `rustc` to learn about target-specific information
Caused by:
  process didn't exit successfully: `sccache rustc - --crate-name ___ --print=file-names --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg` (exit code: 2)
  --- stderr
  error: failed to execute compile
  caused by: Failed to send data to or receive data from server
  caused by: Failed to read response header
  caused by: failed to fill whole buffer
```

not _sure_ what has happened but somehow a CI image rebuild has broken sccache everywhere for us.

**Comment by drahnr** [comment] 2020-11-11 07:34
@ryankurte `v0.2.13` does not have channel/version detection rustc, you have to use the `master` branch for that.

**Comment by glandium** [comment] 2020-12-11 04:32
I'm going to close this issue as the problem is fixed on master. The remaining part is for the fix to make it to a release, which I'm going to cut before the end of year.

**Closed by glandium** 2020-12-11 04:32 UTC
