### ISSUE TITLE
Seeing non-cacheable calls -- what am I doing wrong?

### ISSUE THREAD

**Issue by razeh** [mozilla/sccache#278] opened 2018-08-24 17:10 UTC
I'm compiling a small C++ program with:
  sccache g++ -c raw.C -o raw.o

But the stats show it being non-cacheable:
sccache --show-stats                                                                                                        
Compile requests                 2
Compile requests executed        0
Cache hits                       0
Cache misses                     0
Cache timeouts                   0
Cache read errors                0
Forced recaches                  0
Cache write errors               0
Compilation failures             0
Cache errors                     0
Non-cacheable compilations       0
Non-cacheable calls              2
Non-compilation calls            0
Unsupported compiler calls       0
Average cache write          0.000 s
Average cache read miss      0.000 s
Average cache read hit       0.000 s
Cache location             Local disk: "/home/razeh/.cache/sccache"
Cache size                       0 bytes
Max cache size                  10 GiB

What am I doing wrong?

**Comment by luser** [comment] 2018-08-24 19:19
It's a very silly thing, but this is due to https://github.com/mozilla/sccache/issues/127 . Also: I have a patch that hasn't landed yet that will show the reasons why caching fails in the `--show-stats` output, which will help diagnosing this!

**Comment by luser** [comment] 2018-08-28 14:53
I'm going to close this as a duplicate of #127.

**Closed by luser** 2018-08-28 14:53 UTC
Labels: duplicate
