### ISSUE TITLE
Version 0.5.1 cannot be compiled

### ISSUE THREAD

**Issue by avysk** [mozilla/sccache#1786] opened 2023-06-02 12:07 UTC
`cargo install sccache` =>

```
[blah]
   Compiling sccache v0.5.1
error[E0277]: the trait bound `TaskClusterTokenLoader: reqsign::google::token::TokenLoad` is not satisfied
  --> /home/alexey/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sccache-0.5.1/src/cache/gcs.rs:69:43
   |
69 |               builder.customed_token_loader(Box::new(TaskClusterTokenLoader {
   |  ___________________________________________^
70 | |                 scope: rw_mode.to_scope().to_string(),
71 | |                 url: cred_url.to_string(),
72 | |             }));
   | |______________^ the trait `reqsign::google::token::TokenLoad` is not implemented for `TaskClusterTokenLoader`
   |
   = note: required for the cast from `Box<TaskClusterTokenLoader>` to `Box<(dyn reqsign::google::token::TokenLoad + 'static)>`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `sccache` (lib) due to previous error
```

**Comment by sylvestre** [comment] 2023-06-02 12:10
try "cargo install sccache --locked"

**Comment by avysk** [comment] 2023-06-02 12:13
The same result both on Windows 11 and FreeBSD 12.2, with both stable and nightly toolchains.

**Comment by avysk** [comment] 2023-06-02 12:14
I'll try locked now.

**Comment by avysk** [comment] 2023-06-02 12:19
Worked on FreeBSD with stable toolchain, trying Windows + nightly now.

**Comment by avysk** [comment] 2023-06-02 12:25
Worked as well. Thanks, it was a fast answer!

**Comment by dmilith** [comment] 2023-06-02 13:45
@Foorack Because without --locked cargo uses the most recent (compatible) versions of crates used. With --locked it sticks with exact versions from Cargo.lock.

**Comment by jonasbb** [comment] 2023-06-02 15:09
This seems to be caused by a bad version of `opendal`: https://github.com/apache/incubator-opendal/issues/2403
They bumped the public `reqsign` dependency, without doing a major version bump themselves.

**Comment by sylvestre** [comment] 2023-06-02 15:13
@Xuanwo can help :)

**Comment by Xuanwo** [comment] 2023-06-02 15:19
OpenDAL v0.36.1 has been yanked. Sorry for the trouble.

**Comment by mouse07410** [comment] 2023-06-02 15:27
Sorry, still doesn't work:
```text
$ rustup show
Default host: aarch64-apple-darwin
rustup home:  /Users/ur20980/.rustup

stable-aarch64-apple-darwin (default)
rustc 1.70.0 (90c541806 2023-05-31)
$ 
$ cargo install sccache --locked
    Updating crates.io index
  Installing sccache v0.5.1
    Updating crates.io index
error: failed to get `parking_lot` as a dependency of package `opendal v0.36.0`
    ... which satisfies dependency `opendal = "^0.36.0"` (locked to 0.36.0) of package `sccache v0.5.1`

Caused by:
  failed to query replaced source registry `crates-io`

Caused by:
  download of pa/rk/parking_lot failed

Caused by:
  failed to download from `https://index.crates.io/pa/rk/parking_lot`

Caused by:
  [2] Failed initialization ([CONN-1-0] send: no filter connected)
```

MacOS Ventura 13.4, Apple Silicon M2 platform.

**Comment by Xuanwo** [comment] 2023-06-02 15:39
> $ cargo install sccache --locked
>     Updating crates.io index
>   Installing sccache v0.5.1
>     Updating crates.io index
> error: failed to get `parking_lot` as a dependency of package `opendal v0.36.0`
>     ... which satisfies dependency `opendal = "^0.36.0"` (locked to 0.36.0) of package `sccache v0.5.1`
> 
> Caused by:
>   failed to query replaced source registry `crates-io`
> 
> Caused by:
>   download of pa/rk/parking_lot failed
> 
> Caused by:
>   failed to download from `https://index.crates.io/pa/rk/parking_lot`
> 
> Caused by:
>   [2] Failed initialization ([CONN-1-0] send: no filter connected)

I think this error is not related to opendal or sccache.

**Comment by mouse07410** [comment] 2023-06-02 16:16
> I think this error is not related to opendal or sccache, seems something happened during download package.

I cannot know - but this error is consistent for the last two days.

**Comment by Be-ing** [comment] 2023-06-02 21:46
@mouse07410 The error you are seeing might be related to the switch to the sparse protocol for crates.io by default in Rust 1.70. Try `rm -rf ~/.cargo/registry`

**Comment by mouse07410** [comment] 2023-06-02 22:08
> Try `rm -rf ~/.cargo/registry`

It will not blow all the _other_ installed packages and such, will it? 

Otherwise, how would I recover the registry?

**Comment by Be-ing** [comment] 2023-06-02 22:14
Whatever you need to download will be redownloaded the next time you run `cargo build` or `cargo install`. My guess is that you are encountering a bug in the transition from the old protocol to the new sparse protocol.

**Comment by mouse07410** [comment] 2023-06-02 22:43
```text
$ rm -rf ~/.cargo/registry 
$ cargo install sccache --locked
    Updating crates.io index
  Downloaded sccache v0.5.1
  Downloaded 1 crate (303.2 KB) in 0.61s
  Installing sccache v0.5.1
    Updating crates.io index
error: failed to get `time` as a dependency of package `rouille v3.6.1`
    ... which satisfies dependency `rouille = "^3.5"` (locked to 3.6.1) of package `sccache v0.5.1`

Caused by:
  failed to query replaced source registry `crates-io`

Caused by:
  download of ti/me/time failed

Caused by:
  failed to download from `https://index.crates.io/ti/me/time`

Caused by:
  [2] Failed initialization ([CONN-1-0] send: no filter connected)
$ 
```

**Comment by Xuanwo** [comment] 2023-06-05 05:43
This issue has been fixed now.

The "Failed initialization" error is related to Cargo. For more discussion on this issue, please visit the following link: https://github.com/rust-lang/cargo/issues/12202. Thank you!

**Closed by Xuanwo** 2023-06-05 05:43 UTC
