### ISSUE TITLE
Network-related compilation failure when sccache is involved

### ISSUE THREAD

**Issue by staktrace** [mozilla/sccache#344] opened 2018-12-12 00:06 UTC
https://tools.taskcluster.net/groups/crYJAL7LQbCIKc3jwJsoxA/tasks/SiksqocTRvqvntrgRNu3NQ/runs/0/logs/public%2Flogs%2Flive_backing.log ends in a failure with some sort of network-related error. There's an sccache.log file in the task run artifacts that might provide additional information.

**Comment by staktrace** [comment] 2018-12-12 13:52
Another: https://tools.taskcluster.net/groups/CSHdnQ-_TamNViQHK2cPsw/tasks/XY-6dZ5HS3OmMvfBouAbxw/details

**Comment by jrmuizel** [comment] 2018-12-12 15:04
See also https://github.com/servo/webrender/pull/3402

**Comment by luser** [comment] 2018-12-12 16:19
The sccache.log doesn't have timestamps (I should fix that) but it does show:
```
DEBUG:sccache::compiler::compiler: [webrender]: Compiled in 184.985 s, storing in cache
TRACE:sccache::cache::disk: DiskCache::finish_put(7384495f94501155aa17df4e089afd9e7a4d44634fa72bb4ce972cc8e2c88449f0b00a1e5edf39467d36396c1d9be4f871d0377a77ee9c16b283beaa6b0cd0c5)
TRACE:sccache::server: CompileFinished retcode: exit code: 0
DEBUG:sccache::compiler::compiler: [webrender]: Stored in cache successfully!
DEBUG:sccache::server: [webrender]: Cache write finished in 1.539 s
INFO:sccache::server: shutting down due to being idle or request
```

I think this is a dupe of #204 (which I should find time to fix). We can work around this in the same way we do in Firefox CI by setting `SCCACHE_IDLE_TIMEOUT=0`.

**Closed by luser** 2018-12-12 16:19 UTC

**Comment by luser** [comment] 2018-12-12 16:21
I sent you a PR to do that: https://github.com/servo/webrender/pull/3403
