### ISSUE TITLE
sccache doesn't use seem to always check for rustc versions when caching

### ISSUE THREAD

**Issue by elichai** [mozilla/sccache#741] opened 2020-05-07 10:42 UTC
Hi,
I got problems setting up miri, it complained that some dependencies were compiled by a different rustc version.

See https://github.com/rust-lang/miri/issues/1399
so it seems that the cache doesn't always take into account a change in compiler version?

**Comment by froydnj** [comment] 2020-05-07 10:55
Is this with `sccache` `HEAD` or a released version?

**Comment by elichai** [comment] 2020-05-07 10:55
latest released

**Comment by froydnj** [comment] 2020-05-07 11:08
OK, this issue should be fixed in current git `HEAD`.  Please try with that instead.

**Comment by froydnj** [comment] 2020-05-22 13:16
Assuming that this is fixed on `HEAD`.  Please reopen if this is not the case, with steps to reproduce.

**Closed by froydnj** 2020-05-22 13:16 UTC

**Comment by P1119r1m** [comment] 2024-03-04 09:39
@froydnj Dear Nathan, our team faced the same problem with:
```
wget https://github.com/mozilla/sccache/releases/download/v0.7.7/sccache-v0.7.7-x86_64-unknown-linux-musl.tar.gz
```

The error is following:
```
   Compiling rustc-std-workspace-core v1.99.0 (/WORKSPACE/rust/library/rustc-std-workspace-core)
error[E0514]: found crate `core` compiled by an incompatible version of rustc
 --> library/rustc-std-workspace-core/lib.rs:4:9
  |
4 | pub use core::*;
  |         ^^^^
  |
```

We compiled the old Rust compiler (1.64.0) with "sccache" enabled.
Then switched to compiling a newer version of the Rust compiler (1.65.0) and the build crashed.
If turn "sccache" off everything works fine.

Could you please check "sccache"?
Is it possible that your fix was accidentally deleted or corrupted by someone?

Thank you!

**Comment by froydnj** [comment] 2024-03-04 14:07
> We compiled the old Rust compiler (1.64.0) with "sccache" enabled. Then switched to compiling a newer version of the Rust compiler (1.65.0) and the build crashed. If turn "sccache" off everything works fine.
> 
> Could you please check "sccache"? Is it possible that your fix was accidentally deleted or corrupted by someone?

Hi @P1119r1m !

I don't recall fixing this specifically, and looking through my previous commits to this project, nothing jumps out as obviously fixing this issue.  (I didn't look at the list of commits made around that time by other people.)  It's possible that `rustc` changed something that `sccache` now needs to take into account; it's possible than the version of `sccache` that you were upgrading from needs its cache wiped to start afresh.  I'm not sure what the problem is--though it looks like you might be compiling parts of `rustc` itself, and I'm guessing that might be a little tricky, given that paths to different versions of the compiler might be the same from build to build, despite the underlying contents of the compiler being different.  Versioning might not be as strict with development versions of the compiler, either.

I no longer work on `sccache`, so if after some troubleshooting, you are still encountering problems, you should open a new issue with steps to reproduce.

**Comment by P1119r1m** [comment] 2024-03-04 15:32
@froydnj Thanks for the quick reply! I appreciate this.
As far as I can see, there is a problem.
I will prepare the "steps to reproduce the issue" and create a separate Issue as you suggested.
I understand that you are no longer working on this project.
In any case, thanks!
