### ISSUE TITLE
Firefox build failures on OS X when clang preprocessor output is compiled

### ISSUE THREAD

**Issue by na-g** [mozilla/sccache#117] opened 2017-05-03 03:12 UTC
When building Firefox for OS X using sccache and clang, there is at least one compilation unit that fails complaining of duplicated symbols. I disabled the check for -Werror that allows compiling from preprocessor output. It rebuilt successfully.

File that failed: media/libav/libavcodec/avfft.c

details: macOS 10.12.4, latest sccache, mozilla-inbound @ c29534e2e891

Sccache log snippets:
[sccache_build_failure_sccache_log_snippets.txt](https://github.com/mozilla/sccache/files/972393/sccache_build_failure_sccache_log_snippets.txt)

Mozconfig:
[sccache.opt.mozconfig.txt](https://github.com/mozilla/sccache/files/972384/sccache.opt.mozconfig.txt)

Portion of the build log in question:
[sccache_build_failure.log.txt](https://github.com/mozilla/sccache/files/972387/sccache_build_failure.log.txt)

The results of ./mach build-backend -b CompileDB
[with_sccache_compile_commands.json.txt](https://github.com/mozilla/sccache/files/972378/with_sccache_compile_commands.json.txt)

I am using the S3 storage backend against a network local instance of Minio.

**Comment by luser** [comment] 2017-06-09 16:17
I just hit this locally, I hadn't tried to build Firefox with sccache on OS X in a while. The problem is that this file is compiled with `-include avfft_perms.h`, which does a `#include "avfft.h"`. sccache preprocesses the source file, then tries to compile it from the preprocessed source, but passes `-include avfft_perms.h` again, which results in the duplicate definitions. I suspect this works in CI because we build with `--enable-warnings-as-errors` there, and we have special handling for falling back to compiling from the original source when we fail to compile and `-Werror` is in the commandline.

Here's a simpler testcase that reproduces the issue:
```
luser@eye7:/tmp/sccache-test$ touch test.c
luser@eye7:/tmp/sccache-test$ echo "struct S {};" > test.h
luser@eye7:/tmp/sccache-test$ /build/sccache/target/x86_64-unknown-linux-musl/release/sccache /build/clang+llvm-4.0.0-x86_64-linux-gnu-ubuntu-16.10/bin/clang -o test.o -c test.c -include test.h
In file included from test.c:1:
In file included from <built-in>:1:
./test.h:1:8: error: redefinition of 'S'
struct S {};
       ^
./test.h:1:8: note: previous definition is here
struct S {};
       ^
1 error generated.
```

**Comment by glandium** [comment] 2017-07-15 23:10
There are two combined problems in sccache:
- It doesn't treat arguments like `-I`, `-include`, `-idirafter`, etc. as preprocessor flags.
- It doesn't even see most uses of `-I` in the main loop that treats argument, because most uses are of the form `-Ifoo`, while the loop looks for `-I foo` (it considers `-I` as having a separate argument, and `-Isomething` is considered as an unknown argument). The core problem is that many of the preprocessor args allow "concatenated" arguments, like `-Ifoo`: `-I foo` and `-Ifoo` mean the same thing. But that's not limited to `-I`: `-includefoo` and `-include foo` mean the same thing too. That's valid for all the arguments marked `TAKES_CONCAT_ARG` in https://github.com/ccache/ccache/blob/master/compopt.c#L32-L84 . So even trying to treat those flags as preprocessor flags in sccache would need a refactor to take that into account.

The quick and dirty fix, though, would just be to add `-include` to preprocessor_args instead of common_args.

**Comment by glandium** [comment] 2017-07-15 23:11
I'm tempted to rewrite the argument parsing with a macro...

**Comment by luser** [comment] 2017-07-17 15:16
For Rust compilation I wrote an iterator implementation that splits arguments into (argument, value) pairs:
https://github.com/mozilla/sccache/blob/5a4ea952021443a7eb6e13cf16391ef92ea0ca98/src/compiler/rust.rs#L337

That's slightly simplified by the fact that rustc's argument parsing isn't ridiculous, but we could do the same thing for the C compilers and special-case all those `TAKES_CONCAT_ARG` arguments.

**Comment by luser** [comment] 2017-07-17 15:17
> The quick and dirty fix, though, would just be to add -include to preprocessor_args instead of common_args.

I think it'd be good to take a quick fix for this because it's actually breaking things, and then do a better fix for the other issues you've enumerated in a follow-up.

**Comment by glandium** [comment] 2017-07-24 23:33
Ok, so the *actual* problem is that `-x cpp-output` is passed to gcc, but not to clang. The downside is that doing that without actually fixing https://github.com/mozilla/sccache/issues/117#issuecomment-315569559 leads to clang complaining a *lot* about
```
clang: warning: argument unused during compilation: '-include test.h'
clang: warning: argument unused during compilation: '-I foo'
```

**Comment by glandium** [comment] 2017-07-24 23:38
So, let's work around this in a silentish way, then we should fix https://github.com/mozilla/sccache/issues/117#issuecomment-315569559 and *then* we can add `-x cpp-output`.

**Closed** 2017-07-25 10:47 UTC
