### ISSUE TITLE
sccache never has cache hits when invoked through cargo

### ISSUE THREAD

**Issue by CrendKing** [mozilla/sccache#193] opened 2017-10-21 04:45 UTC
I have Rust 1.22 nightly installed. I installed sccache with `cargo install sccache` (sccache 0.2.1). I followed instruction to set up `RUSTC_WRAPPER=sccache`. When building Rust project, no matter how many time I rebuild, sccache never has cache hits. My OS is Windows 10.

Here is an simple example. I create a snippet project with one dependency and no transitive dependency:
```
[dependencies]
itoa = "0.3.4"
```
I run `cargo build -v` several times and here is output:
```
PS C:\workspace\Rust\snippet> rm "C:\workspace\Rust\cargo_target\debug\deps\libitoa-2222172442e22589.rlib"; cargo build -v
   Compiling itoa v0.3.4
     Running `sccache rustc --crate-name itoa C:\Cargo\registry\src\github.com-1ecc6299db9ec823\itoa-0.3.4\src\lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=2222172442e22589 -C extra-filename=-2222172442e22589 --out-dir C:\workspace\Rust\cargo_target\debug\deps -L dependency=C:\workspace\Rust\cargo_target\debug\deps --cap-lints allow`
   Compiling snippet v0.1.0 (file:///E:/Development/Rust/snippet)
     Running `sccache rustc --crate-name snippet src\main.rs --crate-type bin --emit=dep-info,link -C debuginfo=2 -C metadata=b6d470e9ce94d2a5 -C extra-filename=-b6d470e9ce94d2a5 --out-dir C:\workspace\Rust\cargo_target\debug\deps -L dependency=C:\workspace\Rust\cargo_target\debug\deps --extern itoa=C:\workspace\Rust\cargo_target\debug\deps\libitoa-2222172442e22589.rlib`
    Finished dev [unoptimized + debuginfo] target(s) in 1.12 secs

PS C:\workspace\Rust\snippet> rm "C:\workspace\Rust\cargo_target\debug\deps\libitoa-2222172442e22589.rlib"; cargo build -v
   Compiling itoa v0.3.4
     Running `sccache rustc --crate-name itoa C:\Cargo\registry\src\github.com-1ecc6299db9ec823\itoa-0.3.4\src\lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=2222172442e22589 -C extra-filename=-2222172442e22589 --out-dir C:\workspace\Rust\cargo_target\debug\deps -L dependency=C:\workspace\Rust\cargo_target\debug\deps --cap-lints allow`
   Compiling snippet v0.1.0 (file:///E:/Development/Rust/snippet)
     Running `sccache rustc --crate-name snippet src\main.rs --crate-type bin --emit=dep-info,link -C debuginfo=2 -C metadata=b6d470e9ce94d2a5 -C extra-filename=-b6d470e9ce94d2a5 --out-dir C:\workspace\Rust\cargo_target\debug\deps -L dependency=C:\workspace\Rust\cargo_target\debug\deps --extern itoa=C:\workspace\Rust\cargo_target\debug\deps\libitoa-2222172442e22589.rlib`
    Finished dev [unoptimized + debuginfo] target(s) in 1.11 secs

PS C:\workspace\Rust\snippet> rm "C:\workspace\Rust\cargo_target\debug\deps\libitoa-2222172442e22589.rlib"; cargo build -v
   Compiling itoa v0.3.4
     Running `sccache rustc --crate-name itoa C:\Cargo\registry\src\github.com-1ecc6299db9ec823\itoa-0.3.4\src\lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=2222172442e22589 -C extra-filename=-2222172442e22589 --out-dir C:\workspace\Rust\cargo_target\debug\deps -L dependency=C:\workspace\Rust\cargo_target\debug\deps --cap-lints allow`
   Compiling snippet v0.1.0 (file:///E:/Development/Rust/snippet)
     Running `sccache rustc --crate-name snippet src\main.rs --crate-type bin --emit=dep-info,link -C debuginfo=2 -C metadata=b6d470e9ce94d2a5 -C extra-filename=-b6d470e9ce94d2a5 --out-dir C:\workspace\Rust\cargo_target\debug\deps -L dependency=C:\workspace\Rust\cargo_target\debug\deps --extern itoa=C:\workspace\Rust\cargo_target\debug\deps\libitoa-2222172442e22589.rlib`
    Finished dev [unoptimized + debuginfo] target(s) in 1.10 secs

PS C:\> sccache -s
Compile requests                19
Compile requests executed        5
Cache hits                       0
Cache misses                     5
Cache timeouts                   0
Cache read errors                0
Forced recaches                  0
Cache write errors               0
Compilation failures             0
Cache errors                     0
Non-cacheable compilations       0
Non-cacheable calls             14
Non-compilation calls            0
Unsupported compiler calls       0
Average cache write          0.001 s
Average cache read miss      0.397 s
Average cache read hit       0.000 s
```
Notice I remove the compiled dependency before I run `cargo build`, and the time spent is exactly same.

Now if I directly run the first line
```
sccache rustc --crate-name itoa C:\Cargo\registry\src\github.com-1ecc6299db9ec823\itoa-0.3.4\src\lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=2222172442e22589 -C extra-filename=-2222172442e22589 --out-dir C:\workspace\Rust\cargo_target\debug\deps -L dependency=C:\workspace\Rust\cargo_target\debug\deps --cap-lints allow
```
suddenly I start to get cache hits. So it looks like cargo is the culprit for the problem.

**Comment by luser** [comment] 2017-10-23 10:33
[We noticed this same regression](https://bugzilla.mozilla.org/show_bug.cgi?id=1408836) when updating to Rust 1.20 in Firefox automation, but I haven't found time to track it down yet.

**Comment by luser** [comment] 2017-10-25 09:57
Is that `snippet` crate you're testing with literally just an empty Rust crate with that one dependency in Cargo.toml?

**Comment by CrendKing** [comment] 2017-10-25 17:29
Yes. Empty main function. One dependency. Here is the Cargo.lock:
```
[root]
name = "snippet"
version = "0.1.0"
dependencies = [
 "itoa 0.3.4 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "itoa"
version = "0.3.4"
source = "registry+https://github.com/rust-lang/crates.io-index"

[metadata]
"checksum itoa 0.3.4 (registry+https://github.com/rust-lang/crates.io-index)" = "8324a32baf01e2ae060e9de58ed0bc2320c9a2833491ee36cd3b4c414de4db8c"
```

**Comment by luser** [comment] 2017-10-25 18:12
I tried this locally and figured it out. Since cargo gained jobserver support, it now passes a `CARGO_MAKEFLAGS` env var which is different for every build. sccache uses all env vars starting with `CARGO_` as inputs to the hash key for Rust compilation, so this was mucking things up. I have a patch, I'll get it landed shortly.

**Closed** 2017-10-25 19:13 UTC

**Comment by luser** [comment] 2017-10-25 20:05
Thanks for the bug report! Knowing that this bug manifested with a basically-empty crate made it much easier to diagnose than trying to build all of Firefox. :)

**Comment by CrendKing** [comment] 2017-10-25 23:12
Just to be sure, since this is easy to reproduce, could you add test to prevent regression? There could be new env variable introduce in the future that is volatile and should trigger test failure.

Also, is using all CARGO_ env variable as part of key input good design? Is it possible to identify a set of core variables and only relying on those? Basically I'm saying, instead of doing blacklisting, should we do whitelisting.

Anyway, thanks for fixing.

**Comment by luser** [comment] 2017-10-26 01:14
> Just to be sure, since this is easy to reproduce, could you add test to prevent regression? There could be new env variable introduce in the future that is volatile and should trigger test failure.

Yes, I did exactly that: https://github.com/mozilla/sccache/blob/2d9bdc1e8fb1fa5a531da2930670bbfcb66f78a0/tests/sccache_cargo.rs#L48

Not having that kind of test in the first place was a pretty big oversight on my part!

> Also, is using all CARGO_ env variable as part of key input good design? Is it possible to identify a set of core variables and only relying on those? Basically I'm saying, instead of doing blacklisting, should we do whitelisting.

The unfortunate thing here is that Rust code can use *any* environment variable via the `env!` macro, so this actually isn't comprehensive enough! Ideally there'd be some way for rustc to tell us what environment variables are referenced, but I chose this as a compromise that should cover most scenarios that happen in practice.
