### ISSUE TITLE
sccache v0.2.13 does not work when built with rustc 1.48

### ISSUE THREAD

**Issue by SomeoneToIgnore** [mozilla/sccache#887] opened 2020-11-20 10:18 UTC
The same dummy "hello world" project + sccache does not work for rustc 1.48 but works for 1.47.

Here's a minimal example:

Create the script locally:
```bash
#! /usr/bin/env bash

set -e
set -x

env USER=test-user cargo new test-project --bin
cd test-project
echo "Running without sccache"
cargo run
cargo clean
cargo install sccache
echo "Running with sccache"
RUSTC_WRAPPER="/usr/local/cargo/bin/sccache" cargo run
sccache -s
```

and then run it in Docker:

`docker run --rm -v $(pwd)/test-sccache.sh:/test-sccache.sh rust:1.47 /test-sccache.sh`

`docker run --rm -v $(pwd)/test-sccache.sh:/test-sccache.sh rust:1.48 /test-sccache.sh`

Expected: both runs work identically and finish successfully

Actual: 1.47 version works as expected, 1.48 version fails on the `RUSTC_WRAPPER="/usr/local/cargo/bin/sccache" cargo run` step:

```
Running with sccache
+ echo 'Running with sccache'
+ RUSTC_WRAPPER=/usr/local/cargo/bin/sccache
+ cargo run
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `/usr/local/cargo/bin/sccache rustc - --crate-name ___ --print=file-names --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg` (exit code: 2)
  --- stderr
  error: failed to execute compile
  caused by: Failed to send data to or receive data from server
  caused by: Failed to read response header
  caused by: failed to fill whole buffer
```

**Comment by drahnr** [comment] 2020-11-24 10:32
@SomeoneToIgnore going to look into that later tonight/early tomorrow.

**Comment by SomeoneToIgnore** [comment] 2020-11-24 10:55
It does work actually, thanks for the tip.

So it's the release that we need.

**Comment by drahnr** [comment] 2020-11-24 11:05
See #876

**Comment by bossmc** [comment] 2020-12-03 12:44
In case people are interested this looks like a breaking change in rust 1.48 (https://github.com/rust-lang/rust/pull/71274/) where `mem::uninitialized` now panics if the type can't hold the zero value:

```
$ SCCACHE_LOG=debug SCCACHE_START_SERVER=1 SCCACHE_NO_DAEMON=1 target/debug/sccache
thread 'main' panicked at 'attempted to leave type `linked_hash_map::Node<std::ffi::OsString, u64>` uninitialized, which is invalid', /home/andy/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/mem/mod.rs:658:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

(I assume OsString is a `NonNull<u8>` or similar).

Until (unless?) Mozilla cut a new release there is a pre-built binary alongside each release (e.g. at  https://github.com/mozilla/sccache/releases/tag/0.2.13) that works, or you can use `master` or @drahnr's fork at https://github.com/paritytech/sccache.

**Comment by glandium** [comment] 2020-12-11 04:40
Duplicate of #875

**Closed by glandium** 2020-12-11 04:40 UTC
