### ISSUE TITLE
rustc version detection

### ISSUE THREAD

**Issue by DemiMarie** [mozilla/sccache#853] opened 2020-09-17 16:07 UTC
Currently, `sccache` is not aware of the version of `rustc` that it runs.  Therefore, it is necessary to blow away the cache and start over after any Rust update.

**Comment by luser** [comment] 2020-09-17 18:36
This is a duplicate of #87, should have been fixed by #666. In the general case, sccache includes a hash of the compiler binary (or libs in the rustc case) in the cache key, but that didn't work well with rustup. It should be fixed nowadays.

**Comment by DemiMarie** [comment] 2020-09-17 21:48
Has the case of `+nightly` been fixed?

**Comment by froydnj** [comment] 2020-09-17 22:26
> Has the case of `+nightly` been fixed?

I believe it has; if you have evidence to the contrary of this, please file a separate bug.

**Comment by drahnr** [comment] 2020-09-28 12:05
```
git clone git@github.com:hicommonwealth/edgeware-node.git
cd edgeware-node
git checkout apopiak-migrations-extraction 
rustup override set nightly-2020-06-30
cargo build --release -p edgeware-runtime
rustup override set nightly-2020-07-02
cargo build --release -p edgeware-runtime
```

should reproduces this ( thanks @apopiak )

This is an extension to https://github.com/mozilla/sccache/issues/454 that was  (apparently) not covered in #666

**Comment by glandium** [comment] 2020-12-11 04:31
I'm going to close this issue as the problem is fixed on master. The remaining part is for the fix to make it to a release, which I'm going to cut before the end of year.

**Closed by glandium** 2020-12-11 04:31 UTC
