### ISSUE TITLE
Issue with `-Xclang` and `--` compiling using ninja

### ISSUE THREAD

**Issue by hexhexD** [mozilla/sccache#1559] opened 2023-01-14 00:25 UTC
`C:\Users\scoop\shims\sccache.exe C:\dev\build_with_clang_relwithdbginfo\bin\clang-cl.exe  /nologo -Xclang -fno-rtti -flto -c -- C:\dev\Something.cpp`
The above command yields `clang-cl: fatal error: no such file or directory: '-Xclang'; did you mean '-Xclang'?`. The problem goes away if I remove the `--`. The example line is generated using ninja and I believe the double dash signifies the end of command options.

I'm thinking it might has something todo with how sccache rearranges the arguments after parsing them and somehow put it after "--". I had tried to use "/clang:-fno-rtti" which is the same as -Xclang but "/clang:" is not currently supported by sccache.

**Comment by hexhexd** [comment] 2023-01-14 00:30
Just realized it had been mentioned few days ago #1498

**Comment by glandium** [comment] 2023-11-23 04:31
Duplicate of #1498

**Closed by glandium** 2023-11-23 04:31 UTC
