### ISSUE TITLE
sccache + clang-cl MSVC broken since PR1730 

### ISSUE THREAD

**Issue by omjavaid** [mozilla/sccache#1953] opened 2023-11-13 05:25 UTC
clang-cl fails to compile with sccache appended on latests version 0.5.3. The problem is exactly the same as described in #1725. The problem seems to be fixed for MSVC cl but not for clang-cl. Note: This problem only appeared for clang-cl before the fix.

**Comment by sylvestre** [comment] 2023-11-13 06:52
sorry but could you please share error messages?

**Comment by omjavaid** [comment] 2023-11-13 08:25
`sccache C:\PROGRA~1\LLVM\bin\clang-cl.exe  /nologo -TP -DGTEST_HAS_RTTI=0 -DUNICODE -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_NONSTDC_NO_WARNINGS -D_CRT_SECURE_NO_DEPRECATE -D_CRT_SECURE_NO_WARNINGS -D_GLIBCXX_ASSERTIONS -D_HAS_EXCEPTIONS=0 -D_SCL_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_WARNINGS -D_UNICODE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -IC:\work2\llvm-dev\build\lib\Support -IC:\work2\llvm-dev\llvm-project\llvm\lib\Support -IC:\work2\llvm-dev\build\include -IC:\work2\llvm-dev\llvm-project\llvm\include /DWIN32 /D_WINDOWS   /Zc:inline /Zc:__cplusplus /Oi /Brepro /bigobj /permissive- /W4  -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wmisleading-indentation -Wctad-maybe-unsupported /Gw  /O2 /Ob2  -MD -UNDEBUG -std:c++17  /EHs-c- /GR- /showIncludes /Folib\Support\CMakeFiles\LLVMSupport.dir\AMDGPUMetadata.cpp.obj /Fdlib\Support\CMakeFiles\LLVMSupport.dir\LLVMSupport.pdb -c -- C:\work2\llvm-dev\llvm-project\llvm\lib\Support\AMDGPUMetadata.cpp
clang-cl: error: no such file or directory: '/wd4668'
ninja: build stopped: subcommand failed.`

**Comment by sylvestre** [comment] 2023-11-13 08:27
@Alexei-Barnes you had the same issue, right ? :)

**Comment by omjavaid** [comment] 2023-11-13 08:32
@sylvestre  Before the fix for https://github.com/mozilla/sccache/issues/1725 was posted it used to work for clang-cl but not for cl.exe. Now sccache gives this message with clang-cl while cl works fine.

**Comment by sylvestre** [comment] 2023-11-13 08:35
@omjavaid which fix are you talking about?
https://github.com/mozilla/sccache/issues/1725#issuecomment-1507176887
suggested that it is a compiler bug, not sccache

**Comment by sylvestre** [comment] 2023-11-13 08:49
ok, thanks
seems that the workaround is still there and still tested by the CI:
https://github.com/mozilla/sccache/actions/runs/6825714731/job/18564154401

**Comment by omjavaid** [comment] 2023-11-13 08:53
But same workaround has broken "clang-cl" which used to work before it was merged.

**Comment by sylvestre** [comment] 2023-11-13 08:55
@omjavaid does it work if you revert the PR ? thanks

**Comment by omjavaid** [comment] 2023-11-13 08:58
I have not built sccache from source to test this. I just used one earlier release which appeared to be 0.5.1 to make things work for me.

**Comment by glandium** [comment] 2023-11-14 08:18
You're mentioning versions 0.5.x, have you tried version 0.7.1?

**Comment by omjavaid** [comment] 2023-11-14 08:51
@glandium yes I have tried 0.7.1 and then moved back to 0.5.1 because this was the last release that worked with clang-cl + MSVC.

**Comment by sylvestre** [comment] 2023-11-14 08:57
@omjavaid this is a bit confusing
you opened the ticket mentioning 0.5.3

This error message:
https://github.com/mozilla/sccache/issues/1953#issuecomment-1807664956
is produced with which version?

**Comment by omjavaid** [comment] 2023-11-14 09:23
The offending commit is #1730 which was first merged in version 0.5.2. The problem persists since then till the latest 0.7.1 version.

**Comment by glandium** [comment] 2023-11-14 19:44
Oh, this is a dupe of https://github.com/mozilla/sccache/pull/1856

**Closed by glandium** 2023-11-14 19:44 UTC
