### ISSUE TITLE
sccache: error : Invalid checksum

### ISSUE THREAD

**Issue by ezyang** [mozilla/sccache#738] opened 2020-05-01 21:10 UTC
Occasionally, our sccache invocations will fail with the error "Invalid checksum". Sorry about not having a repro; it happens very rarely. However, if it's related to cache files sccache pulls from the Internet, shouldn't sccache just treat it as a cache miss, in that case?

Example log: https://dr.pytorch.org/api/view-log-full?build_id=114187552

**Comment by froydnj** [comment] 2020-05-02 16:10
Presumably we'd need to extend the error handling here:

https://github.com/mozilla/sccache/blob/27bf3e61c4a82541f794275884a3fb1a3b1fc4f3/src/server.rs#L1179-L1194

to deal with compression errors.  It looks like the code in `errors.rs` doesn't even know about compression errors, so maybe there'd be some work in `flate-rs` or wherever to expose proper errors, and then some plumbing through on the sccache side.

**Comment by adrianimboden** [comment] 2020-06-04 13:44
We use it only locally, and I've also seen this error (only once so far)

**Comment by adrianimboden** [comment] 2020-10-31 00:11
I can reproduce the problem quite easely with our new buildsystem here. Can I do something to help?

**Comment by froydnj** [comment] 2020-11-02 14:47
I think this was fixed by #836?

**Comment by adrianimboden** [comment] 2020-11-03 08:07
ah allright, I need to build it myself then. No release in a long time :)

**Comment by adrianimboden** [comment] 2020-11-10 10:32
I did not see the error anymore here. I think this bugreport can be closed now.

**Comment by glandium** [comment] 2020-12-11 02:36
Closing per https://github.com/mozilla/sccache/issues/738#issuecomment-724614810

**Closed by glandium** 2020-12-11 02:36 UTC
