### ISSUE TITLE
Recognize .C as C++ for gcc/clang

### ISSUE THREAD

**Issue by luser** [mozilla/sccache#127] opened 2017-05-19 18:16 UTC
I saw this in sccache logs building servo, we currently produce `CannotCache(unknown source extension)`. I think these are all autoconf tests that we wouldn't cache anyway for other reasons, but we can at least mostly do the right thing here.

**Comment by mathstuf** [comment] 2020-05-15 15:33
Duplicate of #586 which is fixed via #595.

**Comment by nnethercote** [comment] 2020-06-01 05:33
This issue can be closed, but I don't have permission to close it.

**Closed** 2020-06-01 13:14 UTC
Labels: help wanted
