### ISSUE TITLE
compile fails with syntax syntec errors

### ISSUE THREAD

**Issue by drahnr** [mozilla/sccache#662] opened 2020-02-11 15:32 UTC
Compiling workspace github.com/spearow/juice always fails (`redis -u ... flushall`, delete `target` dir, delete `~/.cache/sccache*` did not change anything)

```
error[E0423]: expected function, tuple struct or tuple variant, found struct `ast::Name`
   --> /home/bernhard/.cargo/registry/src/github.com-1ecc6299db9ec823/syntex_syntax-0.58.1/src/symbol.rs:146:27
    |
146 |                       name: ast::Name($index),
    |                             ^^^^^^^^^
...
165 | / declare_keywords! {
166 | |     // Invalid identifier
167 | |     (0,  Invalid,        "")
168 | |
...   |
231 | |     (56, CrateRoot, "{{root}}")
232 | | }
    | |_- in this macro invocation

error: aborting due to previous error

For more information about this error, try `rustc --explain E0423`.
```

where the versions are:

```bash
$ rustc --version
rustc 1.41.0 (5e1a79984 2020-01-27)
$ cargo --version
cargo 1.41.0 (626f0f40e 2019-12-03)
$ sccache --version
sccache 0.2.13-alpha.0
```

with env
```
RUSTC_WRAPPER=$(which sccache)
SCCACHE_REDIS=redis://...6739
```

**Comment by froydnj** [comment] 2020-02-11 15:50
I cannot reproduce this error with a local disk cache; does it reproduce if you use a local disk cache instead of redis?

**Comment by drahnr** [comment] 2020-02-11 15:58
Just tried, happens also:

```
killall sccache
rm -rf ~/.cargo/registry/{cache,src}
rm -rf ~/.cache/sccache*
rm -rf target/debug
unset SCCACHE_REDIS
# RUSTC_WRAPPER as before
cargo b
```

compiling locally works just fine

**Comment by froydnj** [comment] 2020-02-11 16:24
Ah, I can reproduce this with a local disk cache if I update to Rust 1.41.  @chmanchester, are you able to take a look at this?

**Comment by chmanchester** [comment] 2020-02-11 16:29
Yes, I'll take a look at this later in the day.

**Comment by chmanchester** [comment] 2020-02-11 16:58
I'm having trouble getting that crate to build with rustc 1.41 at all. Running the rustc command generated by cargo for `syntex_syntax` fails in just the same way.

Closing for now, please let me know if I've missed something here that indicates this can be fixed in `sccache`.

**Closed by chmanchester** 2020-02-11 16:58 UTC

**Comment by drahnr** [comment] 2020-02-11 17:17
I think this might be it https://github.com/rust-lang/rust/issues/68729
It's just coincidence that I deleted the cached binary from before the update (does that make sense?)

**Comment by drahnr** [comment] 2020-02-11 17:22
Cause by a outdated peer dependency on bindgen `0.30`
